# Configuration file for OneCraft Plugin
# Plugin requested on Fiverr, made by Macs @ MacsWorks.eu
# For support: macsworks.eu/discord

lang:
  no-permission: "&c[&4!&c] You don't have permission!"     